name: Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write' # For gcp auth

    steps:
    # 1. Cloning repo
    - name: Checkout Repository
      uses: actions/checkout@v4

    # 2. GCP Authentication
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    # 3. Gcloud CLI Installation
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    # 5. Deploying on Cloud Run
    - name: Deploy hello_world_function # Deploy using gcloud functions
      run: gcloud functions deploy test_function --region europe-west1 --source cloud_functions --trigger-http --runtime python39


